---
- name: Create Lidarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ lidarr_data_directory }}"

- name: Lidarr
  docker_container:
    name: lidarr
    image: linuxserver/lidarr
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ lidarr_music_directory }}:/music:rw"
      - "{{ lidarr_download_directory }}/downloads:/downloads:rw"
      - "{{ lidarr_data_directory }}:/config:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "8686:8686"
    env:
      PUID: "{{ lidarr_user_id }}"
      PGID: "{{ lidarr_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
